let products = [{
    id: 1001,
    name: "Test product name",
    place: "Test location",
    slots: 3,
    price: 10,
}, {
    id: 1002,
    name: "Test product name 2",
    place: "Test location over there",
    slots: 3,
    price: 21,
}, {
    id: 1003,
    name: "Test product name 3",
    place: "Test location over there",
    slots: 3,
    price: 21,
}, {
    id: 1004,
    name: "Test product name 4",
    place: "Test location over there",
    slots: 3,
    price: 21,
}, {
    id: 1005,
    name: "Test product name 5",
    place: "Test location over there",
    slots: 3,
    price: 21,
}, {
    id: 1006,
    name: "Test product name 6",
    place: "Test location over there",
    slots: 3,
    price: 21,
}, {
    id: 1007,
    name: "Test product name 7",
    place: "Test location over there",
    slots: 8,
    price: 21,
}, {
    id: 1008,
    name: "Test product name 8",
    place: "Test location over there",
    slots: 3,
    price: 21,
}, {
    id: 1009,
    name: "Test product name 9",
    place: "Test location over there",
    slots: 3,
    price: 21,
}, {
    id: 1010,
    name: "Test product name 9",
    place: "Test location over there",
    slots: 3,
    price: 21,
}]